spring:
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 2

#    Reliable Producer
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true


